services:
  - type: web
    name: panel-pismai
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: APP_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
